from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class FrogChallengeAssets: 


	# Image Rule Assets
	# 庭院右侧青蛙挑战赛入口 
	I_ENTRY = RuleImage(roi_front=(1188,381,38,38), roi_back=(1169,203,78,320), threshold=0.7, method="Template matching", file="./tasks/FrogChallenge/res/fc_entry.png")
	# 活动剧情跳过按钮 
	I_SKIP = RuleImage(roi_front=(1142,27,85,37), roi_back=(1100,0,180,100), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/res/fc_skip.png")
	# 青蛙瓷器挑战赛标题 
	I_TITLE = RuleImage(roi_front=(433,12,312,60), roi_back=(420,0,370,85), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/res/fc_title.png")
	# 挑战按钮 
	I_CHALLENGE = RuleImage(roi_front=(1153,591,72,57), roi_back=(1138,573,100,100), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/res/fc_challenge.png")
	# 活动界面式神录按钮 
	I_SHIKIGAMI_RECORDS = RuleImage(roi_front=(1055,639,46,39), roi_back=(1055,639,46,39), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/res/fc_shikigami_records.png")
	# 10兑换按钮 
	I_EXCHANGE = RuleImage(roi_front=(1107,382,117,37), roi_back=(1107,382,117,37), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/res/fc_exchange.png")
	# 随机御魂选择按钮1 
	I_SELECT_1 = RuleImage(roi_front=(186,519,121,49), roi_back=(186,519,121,49), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/res/fc_select_1.png")
	# 随机御魂选择按钮2 
	I_SELECT_2 = RuleImage(roi_front=(582,519,118,48), roi_back=(582,519,118,48), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/res/fc_select_2.png")
	# 随机御魂选择按钮3 
	I_SELECT_3 = RuleImage(roi_front=(972,519,123,49), roi_back=(972,519,123,49), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/res/fc_select_3.png")
	# 随机御魂购买页面标题 
	I_CHECK_SOUL = RuleImage(roi_front=(400,82,430,34), roi_back=(380,60,480,70), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/res/fc_check_soul.png")
	# 挑战按钮下的免费标签, 表示奖励次数已达上限 
	I_FREE = RuleImage(roi_front=(1148,644,84,38), roi_back=(1090,610,190,110), threshold=0.8, method="Template matching", file="./tasks/FrogChallenge/res/fc_free.png")


	# Ocr Rule Assets


